- name: Install neovim
  become: true
  pacman:
    name: neovim
- name: Create nvim dir
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ user }}/.config"
    - "/home/{{ user }}/.config/nvim"
- name: Copy init.lua for package manager
  copy:
    src: nvim-init-lazy.lua
    dest: "/home/{{ user}}/.config/nvim/init.lua"
- name: Install rust analyzer
  become: true
  pacman:
    name: rust-analyzer
- name: Install ansible language server
  become: true
  pacman:
    name: ansible-language-server
