---
- name: install user packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ user_packages }}"
    use: yay
    state: present
- name: enable services
  become: true
  service:
    name: "{{ item }}"
    enabled: true
  loop: "{{ service_list }}"
- name: OpenSSH key
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    regenerate: never
    type: ed25519