---
- name: Installing aur packages
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ user_packages }}"
    use: yay
    state: present
- name: Enabling services
  become: true
  service:
    name: "{{ item }}"
    enabled: true
  loop: "{{ service_list }}"
- name: Creating ssh folder
  file:
    path: ~/.ssh
    state: directory
- name: Creating OpenSSH key
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_ed25519
    regenerate: never
    type: ed25519