---
- name: Installing aur packages
  become: true
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ user_packages }}"
    use: yay
    state: present
    update_cache: true
- name: Enabling services
  become: true
  service:
    name: "{{ item }}"
    enabled: true
  loop: "{{ service_list }}"
