---
- name: Create sudo group
  become: yes
  group:
    name: sudo
- name: Create docker groups
  become: yes
  group:
    name: docker
- name: Create user
  become: yes
  user:
    create_home: true
    generate_ssh_key: true
    ssh_key_type: ed25519
    groups:
      - sudo
      - docker
    name: "{{ user }}"
    password: ""