---
- name: Create sudo group
  become: yes
  group:
    name: sudo
- name: Create docker groups
  become: yes
  group:
    name: docker
- name: Create user
  become: yes
  user:
    create_home: true
    generate_ssh_key: true
    ssh_key_type: ed25519
    password: "{{ user_password }}"
    groups:
      - sudo
      - docker
    name: "{{ user }}"
- name: Allow 'sudo' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) ALL'
    validate: 'visudo -cf %s'