---
- name: verify yay install
  shell: 
    cmd: yay -h
  ignore_errors: true
  register: yay
  changed_when: false
- name: install yay
  shell:
    cmd: git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si
  when: yay.rc != 0
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'